apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-my-db-secret
  annotations:
     reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical

  target:
    name: my-db-secret

  refreshInterval: "1h"

  data:
    - secretKey: MY_DB
      remoteRef:
        key: MY_DB
