apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: universal-auth-credentials
          clientSecret:
            key: clientSecret
            name: universal-auth-credentials
      secretsScope:
        projectSlug: my-project-v-ja-c # change this with actual project
        environmentSlug: dev # "dev", "staging", "prod", etc..
        secretsPath: / # Root is "/"
        # recursive: true # Default is false
      hostAPI: https://infisical.theinci.in
